exclude:
  - lib
  - config.rb
  - Capfile
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-language-plugin
title: Inklinks of my Heart
tagline: Poems from my Heart
description: >-
  A curated collection of soothing and heart touching poems written by Kamal
  Awasthi.
canonical: 'https://inklinks.me'
url: '//InkLinks.github.io'
owner:
  name: Kamal Awasthi
  avatar: avatar.png
  bio: Poet and Engineer
  email: author@inklinks.me
  twitter: inklinks1
  github: InkLinks
  instagram: inklinks_of_my_heart
  disqus: InkLinks
  location: 'New Delhi, IN'
tools:
  standards: 'HTML, SCSS, Jekyll'
  software: git
opengraph:
  locale: en_US
links:
  - title: About
    url: //about
  - title: English Poems
    url: //english
  - title: Hindi Poems
    url: //hindi
    category:
      title: english
      New field 10: //english
timezone: Asia/Kolkata
future: true
highlighter: pygments
markdown: kramdown
paginate: 3
paginate_path: 'inklinks/page:num'
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  coderay:
    coderay_line_numbers: null
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
sass:
  style: ':compressed'
permalink: '//:categories/:title'
include:
  - .htaccess
theme: jekyll-theme-balzac
