exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*

plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
- jekyll-seo-tag
- jekyll-language-plugin


title:            Inklinks 
tagline:          Poems of my Heart
description:      A curated collection of soothing and heart touching poems written by Kamal Awasthi.
canonical: http://inklinks.me

# Owner/author information
owner:
  name:           Kamal Awasthi
  avatar:         avatar.png
  bio:            "Poet and Engineer"
  email:          author@inklinks.me
  twitter:        kamalawasthi19
  github:         InkLinks
  instagram:      kamal.awasthi      
  disqus:         commentsatmyblog
  location:       "New Delhi, IN"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Poems
    url: http://coletownsend.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
